### ISSUE TITLE
请问有实现多音轨切换的功能的版本吗？

### ISSUE THREAD

**Issue by wolfgold** [dingyuanhong/dui_ffplay#2]

**Comment by dingyuanhong** [comment]
这个我没实现,你可以去修改底层源码 is->audio_stream 的值调整需处理的音频AVStream

**Comment by wolfgold** [comment]
我自己在里面增加了一个audio_stream,实现了这个功能，但是我不知道audio_stream的队列资源释放实在什么位置，导致每一次加载视频，都会有内容泄漏，可否给一些提示。

**Comment by dingyuanhong** [comment]
void FreeVideoState(VideoState **is)
这个函数下面去释放队列资源

**Comment by wolfgold** [comment]
我基本实现了多音轨的功能，内存泄漏也解决了，多谢了。
